/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc
 * - provide next/previous navigation
 */

// @ts-check

const docsFromDir = (label, dirName, options = {}) => ({
  type: 'category',
  label,
  items: [{type: 'autogenerated', dirName}],
  ...options,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    'introduction',
    {
      type: 'category',
      label: '언어',
      collapsed: false,
      items: [
        docsFromDir('Rust', 'Rust'),
        docsFromDir('멀티패러다임 프로그래밍', 'Multi-paradigm Programming'),
      ],
    },
    {
      type: 'category',
      label: '백엔드',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Python 웹',
          items: [
            docsFromDir('Django', 'Django'),
            docsFromDir('Flask', 'Flask'),
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI / Data',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Machine Learning',
          items: [
            docsFromDir(
              'Recommender Systems',
              'Machine Learning/Recommender Systems',
            ),
          ],
        },
        {
          type: 'category',
          label: 'Search & Retrieval',
          items: ['Machine Learning/IR'],
        },
        {
          type: 'category',
          label: 'ML Systems',
          items: ['Machine Learning/MIG-devices'],
        },
      ],
    },
    {
      type: 'category',
      label: '프론트엔드',
      collapsed: false,
      items: [docsFromDir('Blogging', 'Blog')],
    },
    {
      type: 'category',
      label: 'CS',
      collapsed: false,
      items: [
        docsFromDir('Algorithm', 'Algorithm'),
        docsFromDir('Software Engineering', 'Software'),
      ],
    },
    {
      type: 'category',
      label: '인프라 / 환경',
      collapsed: false,
      items: [docsFromDir('WSL', 'WSL')],
    },
    {
      type: 'category',
      label: '개발 도구',
      collapsed: false,
      items: [docsFromDir('IDE / Editor', 'IDE')],
    },
    {
      type: 'category',
      label: '문제 해결',
      collapsed: false,
      items: [docsFromDir('Trouble Shooting', 'Trouble Shooting')],
    },
    {
      type: 'category',
      label: 'Journals',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'Journals'}],
    },
  ],
};

module.exports = sidebars;
